const texto1 = "o meu primeiro nome é";
const primeiroNome = "flavio";
const texto2 = "da família";
const sobrenome = "ferraz";
const texto3 = "minha idade é";
const idade = 20;
const texto4 = "meço";
const altura = 1.77;
const texto5 = "peso";
const peso = 67.8;
const texto6 = "nasci em";
const cidadeNatal = "curitiba";
console.log(texto1);
console.log(primeiroNome);
console.log(texto2);
console.log(sobrenome);
console.log(texto3);
console.log(idade);
console.log(texto4);
console.log(altura);
console.log(texto5);
console.log(peso);
console.log(texto6);
console.log(cidadeNatal);